### ISSUE TITLE
How to use F7ReactComponentExtensions with Component class

### ISSUE THREAD

**Issue by Fire7** [JasonKleban/Framework7.d.ts#32]
Hello! Thanks for you work!

Can you explain how to use `F7ReactComponentExtensions` with `React.Component` in TypeScript ?

```javascript
export default class MyComponent extends React.Component<IProps, IState> {
  componentDidMount() {
    this.$f7.
         ^^^
  TS2339: Property '$f7' does not exist on type 'MyComponent'
  }
```

**Comment by MrAndMrsK** [comment]
Try `extends ...<IProps & F7ReactComponentExtensions, ...>`?  haven’t tested these very new declarations much yet though, so it could very well be broken/wrong besides that.

Jason Kleban

**Comment by MrAndMrsK** [comment]
Ah, right.  Can you also create an empty `interface MyComponent extends F7ReactComponentExtensions { }` so that it is declaration merged in with your class?  Sorry, I’m not near my stuff to experiment.

**Comment by Fire7** [comment]
wow, nice, it's work! Thank you.
Unfortunately `$f7` doesn't implements actual interface of F7.

**Comment by MrAndMrsK** [comment]
cool, but which thing is wrong?  https://framework7.io/react/react-component-extensions.html says it should implement it, right?

But then the Framework7 type is definitely not correct yet.  I just restarted this effort a few days ago and I’ll appreciate any pull requests with corrections.  Otherwise, I’ll keep at it.

Not sure if that’s what you’re talking about it not actually implementing it.
